### ISSUE TITLE
Estafette triggers build on branch creation, although there is no commit done yet

### ISSUE THREAD

**Issue by saquibsayyad** [estafette/estafette-ci#14]
Estafette triggers build every-time a new branch is created, this is of no use as the branch is same as master.

**Comment by JorritSalverda** [comment]
This is very much of use if you're creating release branches from master (or development) if you're following a git workflow like _git flow_ or _gitlab flow_. 

If do this since recently in a lot of estafette components by using a version like:

```
version:
  semver:
    major: 1
    minor: 0
    patch: 0
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.0.0
```

where master is not the release branch but still gets a label like `1.0.0-master-1234` and it's not until you create and push branch `1.0.0` that artifacts with this version are created.

Do you have something in mind to be able to deal with both scenarios?
