### ISSUE TITLE
Allow config to be set using environment variables

### ISSUE THREAD

**Issue by JorritSalverda** [estafette/estafette-ci#38]
This allows config either to be set via `config.yaml` like this:

```yaml
integrations:
  github:
    enable: true
```

Or through an environment variable:

```
ESCI_INTEGRATIONS_GITHUB_ENABLE=true
```

This helps in installing Estafette from scratch.
