### ISSUE TITLE
Allow passing secretDecryptionKey and jwtKey values in base64 encoding

### ISSUE THREAD

**Issue by JorritSalverda** [estafette/estafette-ci#65]
In order to pass `secretDecryptionKey` and `jwtKey` in either plain text or in base64 encoding property `b64encoded` can be set to `true` or `false`.

_Default:_

```yaml
api:
  secret:
    b64encoded: false
    secretDecryptionKey: abc
    jwtKey: def
```

_Base64 encoded:_

```yaml
api:
  secret:
    b64encoded: true
    secretDecryptionKey: YWJjCg==
    jwtKey: ZGVmCg==
```
